name: Build and Push to Docker

on:
  push:
    branches:
      - dev
      - master

jobs:

  create_image:
    name: Create and push image to docker hub
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_HOME_NOTIFICATIONS: zaytsevdv/home-notifications
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: set ENV
        run: |
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
             echo "Create PRODUCTION image"
             echo "::set-env name=APP_POLYGON::prod"
          fi

          if [ "$GITHUB_REF" == "refs/heads/dev" ]; then
              echo "Create DEVELOP image"
              echo "::set-env name=APP_POLYGON::dev"
          fi

      - name: Print ENV
        run: |
          printenv

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_REPO_HOME_NOTIFICATIONS }}:${APP_POLYGON}-latest .

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_REPO_HOME_NOTIFICATIONS }}:${APP_POLYGON}-latest

